# .github/workflows/build-agent.yml

# 파이프라인의 이름
name: Build LLM Logger Agent

# 파이프라인이 실행될 조건: main 브랜치에 코드가 push 될 때마다
on:
  push:
    branches: [ "main" ]

# 실행될 작업(Job) 목록
jobs:
  # 'build-on-windows' 라는 이름의 작업
  build-on-windows:
    # Windows 가상머신 최신 버전에서 실행
    runs-on: windows-latest

    # 단계별(Step) 실행 내용
    steps:
      # 1. GitHub 저장소의 코드를 가상머신으로 내려받기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 3.11 버전 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. requirements.txt 로 라이브러리 설치
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. PyInstaller로 .exe 파일 빌드
      - name: Build with PyInstaller
        run: pyinstaller --onefile --noconsole --name "LLM_Logger_Agent" auto_llm_proxy.py

      # 5. 빌드 결과물(.exe 파일)을 'Artifacts'로 업로드하여 다운로드 가능하게 만들기
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llm-logger-agent-windows
          path: dist/LLM_Logger_Agent.exe